### ISSUE TITLE
organization

### ISSUE THREAD

**Issue by anproulx** [brainhack-school2020/abide-fmri#23]
Hi guys , 

Should we reorganize our abide-fmri repo? Maybe put all our .ipynb in a separate folder... prep data+requirements together? What do you think?

**Comment by emilyemchen** [comment]
yes absolutely! Here's my proposed structure: 
1. jupyter-notebooks (directory)
2. scripts (directory)
3. presentation (directory)
4. README.md
5. requirements.txt
6. LICENSE
7. .gitignore

I can reorganize if you'd like!
@anproulx @mschoettner

**Comment by emilyemchen** [comment]
Completed.
